/**
 * Editable YAML Editor option hints (Hub info buttons).
 *
 * Keys are YAML option names (snake_case), matching data-yaml / Options.py.
 * Option-set section headers use the set key (e.g. doors_to_change).
 * Choice dropdowns can use "optionKey::selectedValue" (e.g. game_goal::all_bosses);
 * the info bubble then shows the hint for the currently selected option.
 *
 * Edit the strings below — the Hub reads window.YAML_OPTION_HINTS.
 */
(function (global) {
  "use strict";

  global.YAML_OPTION_HINTS = {
    "accessibility::items": "Ensure all logically relevant items can be acquired. Some items (e.g. keys) may be self-locking, and some locations may still be inaccessible. Metroid Bread also requires ~90% of clearable checks reachable when Raven Beak opens.",
    "accessibility::full": "Ensure everything can be reached and acquired. Kept only when every AP pickup/event is in logic under your tricks; otherwise generation downgrades this to Items.",
    "accessibility::minimal": "Ensure only what is needed for the goal can be acquired. During generation this is upgraded to Items.",
    "climb_sloped_surfaces": "It is possible to gain height on sloped surfaces with good movement (free-aim, Flash Shift, Spin Boost, or Phantom Cloak).",
    "climb_sloped_tunnels": "Various tunnels that contain slopes in the game can be ascended with bombs or good movement (eg. Charge Beam Room).",
    "combat_tricks": "If enabled, the player may be expected to defeat enemies and bosses with fewer items and less health. Defaults to Beginner so early bosses (e.g. Corpius) are logically clearable without collecting Energy Tanks during accessibility checks.",
    "constant_cold_damage": "Constant cold-room damage per second. 0 = vanilla scaling damage. Randovania starter uses 20.",
    "constant_heat_damage": "Constant heated-room damage per second. 0 = vanilla scaling damage. Randovania starter uses 20.",
    "constant_lava_damage": "Constant lava damage per second. 0 = vanilla scaling damage. Randovania starter uses 20.",
    "cross_bomb_launch": "By sliding and morphing as the Cross Bomb is exploding, Samus gains a lot of horizontal momentum.",
    "cross_bomb_skip": "There are sets of crumble blocks that you must use Cross Bomb to roll across. All can be skipped with the right tools.",
    "damage_boost": "Most enemies will knock you away when Samus gets damaged. This can be used to get momentum over ledges.",
    "death_link": "When you die, other Death Link players die too (and vice versa), if the room has Death Link enabled.",
    "diagonal_bomb_jump": "A special kind of bomb jump where you gain diagonal momentum from bombs that explode slightly to the side.",
    "diffusion_abuse": "Using Diffusion Beam in certain situations can bypass the usual requirements for some objects.",
    "dna_placement": "Where Metroid DNA may be placed when Required Metroid DNA > 0. prefer_emmi locks DNA onto Central Unit / EMMI-defeat pickups when possible.",
    "door_lock_rando": "Randomize the weapon needed to open eligible doors. Both sides of a door always match. Only basic lock types are used (safe for open-dread-rando).",
    "early_morph_ball": "If enabled, Morph Ball will be guaranteed early in the seed.",
    "enable_death_counter": "Track and display how many times you have died this seed.",
    "energy_parts": "Number of Energy Parts in the item pool. Four Energy Parts equal one Energy Tank.",
    "energy_per_tank": "Max energy gained per Energy Tank (and per four Energy Parts when Immediate Energy Parts is off). Default 100.",
    "energy_tanks": "Number of Energy Tanks in the item pool.",
    "flash_shift_included_ammo": "Chain dashes bundled with the main Flash Shift item. Locked at 2 when Vanilla Flash Shift Behaviour is on. When vanilla is off, used only if Require Main Item is on.",
    "flash_shift_skip": "With certain items or movement techniques, the Shutter Platforms can be bypassed without Flash Shift.",
    "flash_shift_upgrade_amount": "How many chain dashes each Flash Shift Upgrade pickup grants (after the base flash).",
    "flash_shift_upgrade_count": "Number of Flash Shift Upgrade pickups in the pool (1–5). Only used when Vanilla Flash Shift Behaviour is off. All N upgrades are always added to the item pool and displace Missile Tank filler 1:1 (same padding bucket), so they are guaranteed placements — not optional leftovers that can be dropped when the pool is full. Classification is filler (chain ammo) like Missile Tanks; they do not consume major progression...",
    "flash_shift_upgrade_requires_main_item": "Only used when Vanilla Flash Shift Behaviour is off. On: Flash Shift Upgrades may be collected early and stack chains, but the ability does not unlock until the main Flash Shift item is collected. Off: the first Flash Shift Upgrade unlocks the ability (progressive major); later upgrades add chains only.",
    "floor_clip": "Many floors can be clipped through with Speed Booster, Flash Shift, and/or Grapple Beam.",
    "game_goal::defeat_raven_beak": "Win by defeating Raven Beak (Itorash). Generation still requires at least 90% of clearable pickup checks in logic when Raven Beak opens.",
    "game_goal::one_hundred_percent": "Collect every check in your slot, then defeat Raven Beak. Generation requires 100% of clearable checks in logic before Raven Beak opens; the client only sends goal when all checks are done and Raven Beak is beaten.",
    "game_goal::all_bosses": "Defeat every combat/story boss (including Z-57 via its pickup), then Raven Beak. Generation keeps the 90% clearance gate and requires every boss in logic; the client only sends goal when all bosses and the game-beaten flag are done.",
    "grapple_movement": "Using Grapple Beam for magnets without Spider Magnet, jumping from the tether, or Grapple Boost.",
    "heat_cold_runs": "You can run through heat and cold rooms without a suit. It depends on your health how long you can stay.",
    "hint_all_dna": "When Required Metroid DNA > 0, Adam / Network Stations reveal where all required DNA are located.",
    "immediate_energy_parts": "When enabled, each Energy Part immediately raises max energy by 1/4 of Energy Per Tank (ODR ``immediate_energy_parts`` / ``Init.bImmediateEnergyParts``). When off, four parts are needed before energy increases (vanilla fragment behavior). Matches Randovania's Immediate Energy Part setting.",
    "include_boss_pickups": "Whether boss and EMMI defeat pickups are AP checks (on by default).",
    "infinite_bomb_jump": "By chaining and timing bomb jumps it's possible to reach the top of a room.",
    "knowledge_tricks": "Some destructible objects have vulnerabilities other than those which the player is informed of. For example, Power Bomb can be used to destroy Enkys or open charge beam doors.",
    "ledge_warp": "A frame perfect trick that allows you to warp to a ledge you have previously been at.",
    "missile_plus_tank_ammo": "Missiles granted by each Missile+ Tank pickup.",
    "missile_plus_tanks": "Number of Missile+ Tanks (+10 missiles each) in the item pool.",
    "missile_tank_ammo": "Missiles granted by each Missile Tank pickup.",
    "missile_tanks": "Number of Missile Tanks (+2 missiles each) in the item pool.",
    "movement_tricks": "Non-obvious movement which can't easily be classified using other tricks. Players may be expected to perform precise jumps and other niche movement optimizations.",
    "nerf_power_bombs": "Power Bomb Limitations (RDV / ODR): Power Bombs no longer open Charge Beam doors or destroy Enkys. Generator logic follows the same restriction.",
    "power_bomb_tank_ammo": "Power Bombs granted by each Power Bomb Tank pickup.",
    "power_bomb_tanks": "Number of Power Bomb Tanks (+1 power bomb each) in the item pool.",
    "progressive_beams": "If enabled, individual beam upgrades (Wide, Plasma, Wave) are replaced with Progressive Beams.",
    "progressive_bombs": "If enabled, Bomb and Cross Bomb are replaced with Progressive Bombs.",
    "progressive_charge": "If enabled, Charge Beam and Diffusion Beam are replaced with Progressive Charge Beam.",
    "progressive_missiles": "If enabled, Super Missile and Ice Missile are replaced with Progressive Missiles.",
    "progressive_spin": "If enabled, Spin Boost and Space Jump are replaced with Progressive Spins.",
    "progressive_suit": "If enabled, Varia Suit and Gravity Suit are replaced with Progressive Suits.",
    "pseudo_wave": "It's possible to fire through solid walls without obtaining Wave Beam.",
    "raven_beak_damage_table": "Adjust Raven Beak damage taken values. Consistent Low / High flatten uneven weapon damage; Unmodified keeps vanilla tables.",
    "required_dna": "How many Metroid DNA must be collected before Raven Beak is logically / in-game accessible. 0 disables the DNA gate (vanilla-style open artifacts).",
    "reverse_grapple_block": "Opening up grapple blocks from the \"wrong\" side is possible.",
    "room_name_display": "When to show the current room name on screen: Never, Always, or With Fade.",
    "short_boost": "Flash Shift can be manipulated to allow you to charge Speed Booster in a smaller area than intended.",
    "show_boss_lifebar": "Show boss health bars during fights.",
    "show_dna_in_hud": "Show collected Metroid DNA count on the HUD when Required DNA > 0.",
    "show_enemy_damage": "Show floating damage numbers dealt to enemies.",
    "show_enemy_life": "Show health bars / life indicators on regular enemies.",
    "show_player_damage": "Show floating damage numbers when Samus takes damage (ODR config.ini ``AIManager.bShowPlayerDamage``). Off = hidden, same as Randovania/ODR.",
    "single_wall_wall_jump": "With this technique it is possible to jump up a single wall all the way up. Requires Morph Ball.",
    "slide_jump": "By sliding off a cliff and jumping right before you fall you'll jump further.",
    "speed_booster_upgrade_count": "Number of Speed Booster Upgrade pickups in the pool (extra Speed Booster charges). 0 = none.",
    "speedbooster_conservation": "Maintaining and chaining Speed Booster through complex and otherwise unintended situations.",
    "stand_on_frozen_enemy": "After you receive the ice missiles you'll be able to freeze some enemies in place allowing you to reach certain spots.",
    "start_inventory_from_pool": "Pull starting inventory items from the item pool (standard Archipelago StartInventoryPool behavior).",
    "start_with_pulse_radar": "Start with Pulse Radar. When off, Pulse Radar is shuffled into the pool.",
    "starting_kit_items": "Max progression items the generator may precollect as a Start Kit so the chosen starting location has enough sphere-0 checks to fill. 0 (default) = never auto-grant Start Kit items. Raise this when using a cramped random start (Morph / Bomb / etc. behind the spawn).",
    "starting_location": "Where Samus begins a new save. default = Artaria Intro (vanilla). random_save_station = pick a random Randovania-valid start (save / map / nav platforms and the intro start). Or choose a specific location.",
    "starting_missiles": "Missile ammo you begin the seed with.",
    "starting_power_bombs": "Power Bomb ammo you begin the seed with.",
    "transport_rando": "Shuffle elevator and shuttle destinations (two-way within type). Teleporters stay vanilla. The Itorash capsule stays on its vanilla Hanubia pairing so transport rando cannot open Raven Beak from a mid-game elevator. Falls back to vanilla if a shuffle strands checks.",
    "vanilla_flash_shift_behaviour": "When enabled, the pool contains a single Flash Shift item that grants the full vanilla ability (Ghost Aura + 2 chain dashes), matching Randovania / ODR. When disabled, Flash Shift uses the upgrade-based system controlled by Flash Shift Upgrade Count and Require Main Item.",
    "wall_jump_tricks": "Basic movement ability which can be abused in unintended ways.",
    "water_bomb_jump": "Performing a WBJ will make higher bomb jumps underwater possible.",
    "water_space_jump": "Used to gain height underwater in certain places without Gravity Suit.",
    "x_starts_released": "Start with X parasites already released (Elun / freeroam flavor).",
    "yaml_player_name": "Your Archipelago slot / player name. Must match the name used when connecting to the server.",
    "disabled_lights": "Check a region to mass-delete its light actors, making rooms darker there.",
    "change_doors_to": "Which lock types a randomized door may become (beams, missiles, grapple, bombs, Ice/Storm/Diffusion, etc.).",
    "doors_to_change": "Which vanilla door lock types may be randomized when Door Lock Rando is Individual Doors.",
  };
})(typeof window !== "undefined" ? window : globalThis);
